# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - visualstudio
  - vstest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactName: 'drop'
  nugetVersion: 5.3.1

steps:
- task: NuGetToolInstaller@1
  displayName: '[Use NuGet $(nugetVersion)]'
  inputs:
    versionSpec: $(nugetVersion)

- task: NuGetCommand@2
  displayName: '[Restore NuGet Packages]'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: '[Build Solution $(buildConfiguration) to Stage]'
  inputs:
    solution: '$(solution)'
    #msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    msbuildArgs: '/nologo /p:DeployOnBuild=true /p:PublishProfile=$(buildConfiguration)-Pipelines'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

#- task: VSTest@2
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  displayName: '[Publish Stage to Artifacts]'
  inputs:
    targetType: filePath
    filePath: 'PublishStage.ps1'
    arguments: '$(Build.ArtifactStagingDirectory) $(sqlConnectionString) $(googleTrackId'

- task: PublishBuildArtifacts@1
  displayName: '[Publish Artifacts to Releases]'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(artifactName)'
    publishLocation: 'Container'
  condition: succeededOrFailed()

# ~End~

